import * as ChamCongs from './cham-congs';
import * as CheDoNhanViens from './che-do-nhan-viens';
import * as CheDos from './che-dos';
import * as ChiNhanhs from './chi-nhanhs';
import * as ChucVus from './chuc-vus';
import * as LichLamViecs from './lich-lam-viecs';
import * as Manufacturers from './manufacturers';
import * as PhongBans from './phong-bans';
import * as PhuCapNhanViens from './phu-cap-nhan-viens';
import * as ProductAttributes from './product-attributes';
import * as ProductCategories from './product-categories';
import * as Products from './products';
export { ChamCongs, CheDoNhanViens, CheDos, ChiNhanhs, ChucVus, LichLamViecs, Manufacturers, PhongBans, PhuCapNhanViens, ProductAttributes, ProductCategories, Products };
